//! Per-target build steps for the GPUI executable.
//!
//! Build scripts are compiled for the *host*, so every branch here keys off
//! `CARGO_CFG_TARGET_OS` rather than `#[cfg]` — a macOS host cross-checking
//! for Windows must take the Windows branch.
//!
//! # macOS: stage the bundled rtorrent runtime beside the executable
//!
//! The runtime is built by `tools/build-rtorrent-macos.sh`, which stages it into
//! `binaries/rtorrent-macos/` at the repo root.
//!
//! It lands at `<target>/<profile>/binaries/rtorrent/`, which is where
//! [`rstorrent_gpui::daemon`] looks for a bare executable — a `.app` keeps it in
//! `Contents/Resources/binaries/rtorrent/` instead, put there by
//! `tools/bundle-gpui-macos.sh`.
//!
//! A missing runtime is a warning, not an error: the app falls back to a system
//! rtorrent, and a developer who has never run the staging script should still
//! be able to build.
//!
//! # Windows: embed the exe icon and VERSIONINFO
//!
//! See [`embed_windows_resources`]. The Windows runtime (a WSL rootfs) is not
//! staged here; `tools/bundle-gpui-windows.ps1` puts it beside the exe.

use std::path::{Component, Path, PathBuf};

/// Where the staging script leaves the runtime, relative to this crate.
const STAGED: &str = "../../binaries/rtorrent-macos";

/// The subdirectory of the target directory the app looks in.
const DESTINATION: &str = "binaries/rtorrent";

fn main() {
    match std::env::var("CARGO_CFG_TARGET_OS").as_deref() {
        Ok("macos") => stage_macos_runtime(),
        Ok("windows") => embed_windows_resources(),
        _ => {}
    }
}

/// Where the Windows icon lives, relative to this crate. The ICNS beside it is
/// `include_bytes!`'d by `src/app_icon.rs` and copied by the macOS bundler.
const WINDOWS_ICON: &str = "assets/icons/icon.ico";

/// Compile and link a resource script carrying the exe icon and VERSIONINFO.
///
/// gpui-pre's own build script already links `resources/windows/gpui.rc`
/// (an `RT_MANIFEST`, ID 1) into every GPUI app, so this script deliberately
/// carries **no manifest** — a second one would collide with it at link time.
/// The IDs used here cannot collide with it (resource IDs are per type):
///
/// - `ICON` ID 1: gpui-pre's Windows platform loads the window-class icon with
///   `LoadImageW(module, MAKEINTRESOURCE(1), IMAGE_ICON, ..)`, so the icon must
///   be ID 1 for the title bar and taskbar to use it; Explorer takes the
///   lowest-numbered icon group for the file icon, which is also this one.
/// - `VERSIONINFO` ID 1: the standard (and only meaningful) ID.
///
/// `embed_resource::compile` links it into this package's binaries only
/// (`cargo:rustc-link-arg-bins`), not the library or test harnesses. The
/// resource compiler is `rc.exe` from the Windows SDK on a Windows host, or
/// `llvm-rc` when cross-checking from another host.
fn embed_windows_resources() {
    let manifest =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let icon = manifest.join(WINDOWS_ICON);
    println!("cargo:rerun-if-changed={}", icon.display());

    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_default();
    let numeric = |key: &str| {
        std::env::var(key)
            .ok()
            .and_then(|part| part.parse::<u16>().ok())
            .unwrap_or(0)
    };
    let (major, minor, patch) = (
        numeric("CARGO_PKG_VERSION_MAJOR"),
        numeric("CARGO_PKG_VERSION_MINOR"),
        numeric("CARGO_PKG_VERSION_PATCH"),
    );

    // Written to OUT_DIR rather than committed so the version tracks
    // Cargo.toml. The icon path is absolute (the resource compiler runs in
    // OUT_DIR), with `\` and `"` escaped for an RC string literal. The
    // VERSIONINFO flags are spelled as numbers so no SDK header is needed
    // (`llvm-rc` cross-checks have no <winver.h>): FILEOS 0x40004 is
    // VOS_NT_WINDOWS32, FILETYPE 0x1 is VFT_APP.
    // FileDescription is what Task Manager shows as the process name.
    let script = format!(
        r#"// Generated by crates/gpui/build.rs; do not edit.
1 ICON "{icon}"

1 VERSIONINFO
FILEVERSION {major},{minor},{patch},0
PRODUCTVERSION {major},{minor},{patch},0
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x0L
FILEOS 0x40004L
FILETYPE 0x1L
FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "FileDescription", "rstorrent"
            VALUE "FileVersion", "{version}"
            VALUE "InternalName", "rstorrent-gpui"
            VALUE "OriginalFilename", "rstorrent-gpui.exe"
            VALUE "ProductName", "rstorrent"
            VALUE "ProductVersion", "{version}"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"#,
        icon = rc_string(&icon.display().to_string()),
        version = rc_string(&version),
    );

    let rc = out_dir.join("rstorrent-gpui-resources.rc");
    if let Err(error) = std::fs::write(&rc, script) {
        panic!("could not write {}: {error}", rc.display());
    }
    // An icon is cosmetic, but a failure here is a broken toolchain or icon
    // file rather than a missing one (gpui-pre already required the same
    // resource compiler for its manifest), so fail loudly instead of
    // shipping an exe with no icon.
    if let Err(error) = embed_resource::compile(&rc, embed_resource::NONE).manifest_optional() {
        panic!("could not compile {}: {error}", rc.display());
    }
}

/// Escape `text` for the inside of an RC string literal.
fn rc_string(text: &str) -> String {
    text.replace('\\', "\\\\").replace('"', "\"\"")
}

fn stage_macos_runtime() {
    let manifest =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let staged = normalize(&manifest.join(STAGED));
    // Watching the directory covers an added or removed dylib, which is what a
    // re-run of the staging script changes.
    println!("cargo:rerun-if-changed={}", staged.display());

    let Some(target_dir) = target_dir() else {
        println!("cargo:warning=could not locate the target directory; the bundled rtorrent was not staged");
        return;
    };

    let destination = target_dir.join(DESTINATION);
    match stage(&staged, &destination) {
        // Silence on success: a build script that warns every time trains people
        // to ignore the warning that matters.
        Ok(Staged::Runtime) => {}
        Ok(Staged::Empty) => warn_missing(&staged),
        Err(error) => {
            println!("cargo:warning=could not stage the bundled rtorrent: {error}");
        }
    }
}

enum Staged {
    /// The daemon itself was copied; the app will prefer it.
    Runtime,
    /// The staging directory exists (its README is committed, so it usually
    /// does) but the runtime has never been built into it.
    Empty,
}

fn warn_missing(staged: &Path) {
    println!(
        "cargo:warning=no bundled rtorrent in {} — the app will fall back to a system \
         install. Run tools/build-rtorrent-macos.sh to build it.",
        staged.display()
    );
}

/// The directory holding this build's outputs, i.e. `<target>/<profile>`.
///
/// `OUT_DIR` is `<target>/<profile>/build/<crate>-<hash>/out`, so the profile
/// directory is three levels up. Nothing sets this but cargo.
fn target_dir() -> Option<PathBuf> {
    let out = PathBuf::from(std::env::var("OUT_DIR").ok()?);
    Some(out.ancestors().nth(3)?.to_path_buf())
}

/// Resolve `..` lexically, so paths in warnings read the way they look on disk.
fn normalize(path: &Path) -> PathBuf {
    let mut resolved = PathBuf::new();
    for part in path.components() {
        match part {
            Component::ParentDir => {
                resolved.pop();
            }
            other => resolved.push(other),
        }
    }
    resolved
}

/// Copy every file of the staged runtime to `destination`.
///
/// # Errors
///
/// Returns the I/O error when the staging directory or a file in it cannot be
/// read or written.
fn stage(staged: &Path, destination: &Path) -> std::io::Result<Staged> {
    if !staged.is_dir() {
        return Ok(Staged::Empty);
    }
    std::fs::create_dir_all(destination)?;

    let mut staged_runtime = false;
    for entry in std::fs::read_dir(staged)? {
        let entry = entry?;
        if !entry.file_type()?.is_file() {
            continue;
        }
        let name = entry.file_name();
        if name == "rtorrent" {
            staged_runtime = true;
        }
        std::fs::copy(entry.path(), destination.join(name))?;
    }

    Ok(if staged_runtime {
        Staged::Runtime
    } else {
        Staged::Empty
    })
}
