#!/usr/bin/env bash
#
# Build rtorrent inside WSL and expose it to the Windows app.
#
# Ubuntu ships rtorrent 0.9.8, which predates a good deal of the XML-RPC surface
# rstorrent calls (`d.multicall2` among others), so this builds from source
# instead. libtorrent and rtorrent version-lock to each other — the upstream
# README is explicit that they must be in sync — so both are pinned to the same
# tag here.
#
# Run from Windows:  wsl.exe -e bash tools/wsl-setup-rtorrent.sh
# It will prompt for your sudo password (apt + `make install` need root).

set -euo pipefail

# Install *for a human*, never for root. Running this with `sudo` would
# otherwise put the config, session and downloads under /root and register the
# service as User=root, which is both wrong and easy to do by accident since
# the script asks for a sudo password partway through anyway.
if [ "$(id -u)" -eq 0 ]; then
  if [ -n "${SUDO_USER:-}" ] && [ "$SUDO_USER" != "root" ]; then
    echo "Re-running as $SUDO_USER (this script installs for a login user, not root)."
    exec sudo -u "$SUDO_USER" -H bash "$0" "$@"
  fi
  echo "Run this as your normal WSL user, not root — it will ask for sudo when needed." >&2
  exit 1
fi

# 0.16.18 or newer is required on current distros: libtorrent <= 0.16.17 aborts
# with "verify_libcurl_internal_wakeup: fd is blocking" on the first tracker
# announce when built against a recent libcurl. Fixed upstream in
# rakshasa/libtorrent#813, which landed in 0.16.18.
VERSION="${RTORRENT_VERSION:-v0.16.18}"
SCGI_PORT="${RTORRENT_SCGI_PORT:-5000}"
BUILD_DIR="${BUILD_DIR:-$HOME/.cache/rstorrent-build}"
JOBS="$(nproc)"

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

if [ ! -d /run/systemd/system ]; then
  echo "systemd is not running in this distro." >&2
  echo "Add the following to /etc/wsl.conf, then run 'wsl.exe --shutdown':" >&2
  echo "  [boot]" >&2
  echo "  systemd=true" >&2
  exit 1
fi

say "Installing build dependencies"
sudo apt-get update -qq
sudo apt-get install -y --no-install-recommends \
  build-essential automake autoconf libtool pkg-config git ca-certificates \
  libssl-dev libcurl4-openssl-dev zlib1g-dev libncurses-dev libcppunit-dev \
  libtinyxml2-dev

# libtorrent and rtorrent live in separate repos but share a tag.
build_project() {
  local repo="$1" src="$BUILD_DIR/$1"
  shift
  local configure_args=("$@")

  say "Building $repo $VERSION"
  mkdir -p "$BUILD_DIR"
  if [ -d "$src/.git" ]; then
    git -C "$src" fetch --tags --quiet origin
  else
    git clone --quiet "https://github.com/rakshasa/$repo.git" "$src"
  fi
  git -C "$src" checkout --quiet "$VERSION"

  cd "$src"
  # A stale tree from an earlier tag would otherwise poison the build.
  git clean -xfdq
  # Neither repo ships a `configure` or an `autogen.sh` at this tag.
  autoreconf -ivf
  ./configure --prefix=/usr/local "${configure_args[@]}"
  make -j"$JOBS"
  sudo make install
}

build_project libtorrent
# Without an XML-RPC backend rtorrent still opens the SCGI port but answers
# every call with "XML-RPC not supported" — which is the entire interface this
# client speaks. tinyxml2 is the lighter of the two available backends.
build_project rtorrent --with-xmlrpc-tinyxml2
sudo ldconfig

say "Writing ~/.rtorrent.rc"
DOWNLOAD_DIR="$HOME/Downloads"
SESSION_DIR="$HOME/.rtorrent/session"
mkdir -p "$DOWNLOAD_DIR" "$SESSION_DIR"

if [ -f "$HOME/.rtorrent.rc" ]; then
  cp "$HOME/.rtorrent.rc" "$HOME/.rtorrent.rc.bak.$(date +%s)"
  echo "  (existing config backed up)"
fi

cat > "$HOME/.rtorrent.rc" <<RC
# Generated by tools/wsl-setup-rtorrent.sh for the rstorrent Windows client.

directory.default.set = $DOWNLOAD_DIR
session.path.set      = $SESSION_DIR

# SCGI is unauthenticated, so it must never leave this machine. Binding to
# loopback inside the VM is enough: WSL's localhostForwarding makes
# 127.0.0.1:$SCGI_PORT reachable from Windows, while the LAN sees nothing.
network.scgi.open_port = 127.0.0.1:$SCGI_PORT

# 0.16.18 moved this under network.listen; the old network.port_range.set now
# only exists when rtorrent is started with -D (deprecated commands).
network.listen.port.range.set = 6881-6899
protocol.pex.set = yes
dht.mode.set     = disable
RC

say "Installing the rtorrent systemd service"
# rtorrent has no daemon mode — it is a curses app and dies without a pty, so
# it has to run inside a terminal multiplexer. `screen -DmU` stays in the
# foreground, which is what Type=simple wants. (dtach looks like a lighter fit
# but exits 1 under systemd without printing anything, so it is not worth the
# debugging.) Keeping the daemon under systemd also stops WSL from shutting the
# VM down the moment the last interactive shell exits.
sudo apt-get install -y --no-install-recommends screen

sudo tee /etc/systemd/system/rtorrent.service >/dev/null <<UNIT
[Unit]
Description=rtorrent (rstorrent backend)
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$HOME
Environment=HOME=$HOME
ExecStart=/usr/bin/screen -DmUS rtorrent /usr/local/bin/rtorrent
# rtorrent saves its session on SIGINT, so stop the whole cgroup with that
# rather than SIGTERM. An explicit ExecStop is wrong here: systemd's \$MAINPID
# is screen's, and it is unset once the process is gone, so \`kill -s INT\`
# would run with no argument and fail the unit on every ordinary stop.
KillSignal=SIGINT
KillMode=control-group
TimeoutStopSec=30
# screen exits 0 even when rtorrent underneath it crashes, so on-failure would
# never fire.
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

sudo systemctl daemon-reload
sudo systemctl enable --now rtorrent.service

say "Verifying"
sleep 2
systemctl is-active --quiet rtorrent.service \
  && echo "  rtorrent.service: active" \
  || { echo "  rtorrent.service failed to start:" >&2
       sudo systemctl status rtorrent.service --no-pager -l >&2; exit 1; }

/usr/local/bin/rtorrent -h 2>&1 | head -1 || true

cat <<DONE

Done.

  Daemon      rtorrent $VERSION, SCGI on 127.0.0.1:$SCGI_PORT (inside WSL)
  Downloads   $DOWNLOAD_DIR
  Attach TUI  screen -r rtorrent            (detach again with Ctrl-a d)

In rstorrent: Preferences -> Connection -> TCP, host 127.0.0.1, port $SCGI_PORT,
then Test connection.
DONE
